'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {JSDOM}=require('jsdom');
async function page({rejectError}={}){
 const dom=new JSDOM(fs.readFileSync(path.join(__dirname,'../public/telegram/leave-reject.html'),'utf8'),{url:'https://example.com/telegram/leave-reject.html?requestId=NP-1&expectedVersion=5',runScripts:'outside-only'});
 const calls=[];let closed=0;dom.window.Telegram={WebApp:{initData:'signed',ready(){},expand(){},close(){closed++;}}};
 dom.window.fetch=async(url,input)=>{calls.push({url,...JSON.parse(input.body),credentials:input.credentials});return {ok:!url.endsWith('reject') || !rejectError,json:async()=>url.endsWith('context')?{request:{ho_ten:'<img src=x onerror=alert(1)>',bo_phan:'Kho',co_so:'Hà Nội'}}:rejectError?{error:rejectError}:{ok:true}};};
 dom.window.eval(fs.readFileSync(path.join(__dirname,'../public/telegram/leave-reject.js'),'utf8'));await new Promise(r=>setImmediate(r));return {dom,calls,closed:()=>closed};
}
test('MiniApp cancel closes without making a mutation and treats request context as text',async()=>{const p=await page();try{assert.equal(p.dom.window.document.getElementById('context').querySelector('img'),null);p.dom.window.document.getElementById('cancel').click();assert.equal(p.closed(),1);assert.equal(p.calls.length,1);assert.equal(p.calls[0].credentials,'omit');}finally{p.dom.window.close();}});
test('MiniApp errors keep the entered reason and allow retry with the original version',async()=>{const p=await page({rejectError:'Đơn đã thay đổi'});try{const doc=p.dom.window.document;doc.getElementById('reason').value='  cần bàn giao  ';doc.getElementById('reject-form').dispatchEvent(new p.dom.window.Event('submit',{cancelable:true}));await new Promise(r=>setImmediate(r));assert.equal(doc.getElementById('reason').value,'  cần bàn giao  ');assert.equal(doc.getElementById('submit').disabled,false);assert.equal(doc.getElementById('feedback').textContent,'Đơn đã thay đổi');assert.equal(p.calls[1].note,'cần bàn giao');assert.equal(p.calls[1].expectedVersion,'5');}finally{p.dom.window.close();}});

test('MiniApp uses employee title and OK action, accepting an empty optional reason',async()=>{const p=await page();try{const doc=p.dom.window.document;assert.equal(doc.querySelector('h1').textContent,'Từ chối <img src=x onerror=alert(1)>');assert.equal(doc.getElementById('submit').textContent,'OK');doc.getElementById('reason').value='   ';doc.getElementById('reject-form').dispatchEvent(new p.dom.window.Event('submit',{cancelable:true}));await new Promise(r=>setImmediate(r));assert.equal(p.calls[1].note,'');assert.equal(doc.getElementById('feedback').textContent,'Đã từ chối yêu cầu.');assert.equal(doc.getElementById('submit').disabled,true);assert.equal(p.closed(),0);await new Promise(r=>setTimeout(r,900));assert.equal(p.closed(),1);}finally{p.dom.window.close();}});
