'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const html=fs.readFileSync(path.join(__dirname,'../../public/humanresources/index.html'),'utf8');
function page(features=['hr.leave.submit','hr.leave','hr.leave.manage','hr.employees','hr.leave.absence.manage']){const d=new JSDOM(html,{runScripts:'outside-only',url:'https://example.test/humanresources/'});
  d.window.TKSNav={can:f=>features.includes(f),handleBranchError:()=>false};
  for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi))if(m[1].trim())d.window.eval(m[1]);
  return d;
}
const response=(data,ok=true,status=200)=>({ok,status,json:async()=>data});
const preview={totalSessions:2,deadlineDate:'2026-10-04',deadlineExclusiveAt:'2026-10-04T17:00:00Z',firstSessionStartAt:'2026-10-06T01:00:00Z',scheduleVersion:'1',timingStatus:'Đúng hạn'};
function dates(w,start='2026-10-06',end='2026-10-07'){for(const [id,v]of Object.entries({slStartDate:start,slEndDate:end,slStartSession:'Sáng',slEndSession:'Chiều',slReason:'Việc nhà'}))w.document.getElementById(id).value=v;
}
const event={preventDefault(){}};
test('timing remains independent after approval and legacy violation is readable without a new violation decision',async()=>{const d=page();
  const w=d.window;
  try{const row={request_id:'A',trang_thai:'Chưa duyệt',canManage:true,decision_version:1,timing_status:'Vi phạm'};
    w.fetch=async(url,o)=>response(o?.method==='PATCH'?{request:{...row,trang_thai:'Đã duyệt'}}:{requests:[row,{...row,request_id:'OLD',trang_thai:'Vi phạm',timing_status:null}],summary:[]});
    await w.loadLeaveRequests();
    assert.equal(w.document.querySelector('.timing-label').textContent,'Vi phạm');
    assert.deepEqual([...w.document.querySelectorAll('select.status-select option')].filter(o=>!o.disabled).map(o=>o.value),['Chưa duyệt','Đã duyệt','Từ chối','Chưa duyệt','Đã duyệt','Từ chối']);
    await w.submitStatusChange(w.document.querySelector('select.status-select'),'A','Đã duyệt');
    assert.equal(w.document.querySelector('#leave-row-A .timing-label').textContent,'Vi phạm');
    assert.equal(w.document.getElementById('statViolation').textContent,'2');
  }finally{d.window.close();
  }});
test('noncontiguous chosen sessions use actual count and server preview deadline',async()=>{const d=page(['hr.leave.submit']);
  const w=d.window;
  try{let payload;
    w.fetch=async(url,o)=>{if(url.includes('/context'))return response({eligible:true,profile:{hoTen:'A'}});
      if(url.includes('/preview'))return response(preview);
      if(o?.method==='POST'){payload=JSON.parse(o.body);
        return response({request:{}});
      }return response({requests:[]});
    };
    await w.openSelfLeave();
    dates(w);
    await w.updateSelfLeavePreview();
    const boxes=[...w.document.querySelectorAll('#selfLeaveSessions input[type=checkbox]')];
    assert.equal(boxes.length,4);
    boxes[1].checked=false;
    boxes[3].checked=false;
    await w.updateSelfLeavePreview(false);
    assert.match(w.document.getElementById('selfLeaveDuration').textContent,/2 buổi/);
    assert.match(w.document.getElementById('selfLeaveDeadline').textContent,/04\/10\/2026/);
    await w.handleSelfLeaveSubmit(event);
    assert.deepEqual(payload.leave_sessions,[{date:'2026-10-06',session:'Sáng'},{date:'2026-10-07',session:'Sáng'}]);
  }finally{d.window.close();
  }});
test('empty custom calendar never sends and date validation rejects rollover or duplicate selections',async()=>{const d=page();
  const w=d.window;
  try{let sends=0;
    w.fetch=async(url,o)=>{if(url.includes('/context'))return response({eligible:true,profile:{hoTen:'A'}});
      if(url.includes('/preview'))return response(preview);
      if(o?.method==='POST')sends++;
      return response({requests:[]});
    };
    await w.openSelfLeave();
    dates(w);
    await w.updateSelfLeavePreview();
    for(const b of w.document.querySelectorAll('#selfLeaveSessions input'))b.checked=false;
    await w.handleSelfLeaveSubmit(event);
    assert.equal(sends,0);
    assert.equal(w.selfLeaveSessions({start_date:'2026-02-30',end_date:'2026-03-01',start_session:'Sáng',end_session:'Chiều'}),null);
    assert.equal(w.selfLeaveSessions({leave_sessions:[{date:'2026-10-06',session:'Sáng'},{date:'2026-10-06',session:'Sáng'}]}),null);
  }finally{d.window.close();
  }});
test('outdated previews cannot overwrite new dates or missing schedule guidance',async()=>{const d=page(['hr.leave.submit']);
  const w=d.window;
  try{const pending=[];
    w.fetch=async(url)=>url.includes('/context')?response({eligible:true,profile:{hoTen:'A'}}):new Promise(resolve=>pending.push(resolve));
    await w.openSelfLeave();
    dates(w);
    const old=w.updateSelfLeavePreview();
    dates(w,'2026-10-08','2026-10-08');
    const newer=w.updateSelfLeavePreview();
    pending[1](response({error:'Chưa cấu hình lịch làm việc'},false,422));
    await newer;
    assert.match(w.document.getElementById('selfLeaveDeadline').textContent,/cấu hình.*lịch/i);
    pending[0](response(preview));
    await old;
    assert.doesNotMatch(w.document.getElementById('selfLeaveDeadline').textContent,/04\/10\/2026/);
  }finally{d.window.close();
  }});
test('own edit uses stored calendar and expected version, stale denial preserves inputs',async()=>{const d=page(['hr.leave.submit']);
  const w=d.window;
  try{let sent;
    const row={request_id:'OWN',canEdit:true,canManage:false,decision_version:7,trang_thai:'Đã duyệt',ly_do:'Cũ',leave_sessions:[{date:'2026-10-06',session:'Sáng'},{date:'2026-10-08',session:'Chiều'}]};
    w.fetch=async(url,o)=>{if(url.includes('/context'))return response({eligible:true,profile:{hoTen:'A'}});
      if(url.includes('/preview'))return response(preview);
      if(url.includes('/resubmit')){sent={url,body:JSON.parse(o.body)};
        return response({error:'Đơn đã thay đổi'},false,409);
      }return response({requests:[row]});
    };
    await w.loadLeaveRequests();
    await w.openSelfLeaveEdit('OWN');
    assert.equal(w.document.querySelectorAll('#selfLeaveSessions input:checked').length,2);
    assert.match(w.document.getElementById('selfLeaveEditNote').textContent,/duyệt lại/i);
    w.document.getElementById('slReason').value='Mới';
    await w.handleSelfLeaveSubmit(event);
    assert.equal(sent.url,'/api/hr/leave-requests/self/OWN/resubmit');
    assert.equal(sent.body.expectedVersion,7);
    assert.equal(w.document.getElementById('slReason').value,'Mới');
    assert.equal(w.document.getElementById('selfLeaveModal').hidden,false);
    assert.equal(w.document.getElementById('selfLeaveSubmit').disabled,false);
  }finally{d.window.close();
  }});
test('unrelated self-only row cannot expose edit or history while own history shows snapshots',async()=>{const d=page(['hr.leave.submit']);
  const w=d.window;
  try{let histories=0;
    const own={request_id:'OWN',canEdit:true,decision_version:1,leave_sessions:[{date:'2026-10-06',session:'Sáng'}]};
    w.fetch=async(url)=>{if(url.includes('/history')){histories++;
        return response({submissions:[{submission_revision:1,thoi_gian_gui:'2026-10-05T18:30:00Z',leave_sessions:own.leave_sessions,tong_buoi_nghi:1,registration_deadline_date:'2026-10-04',first_session_start_at:'2026-10-06T01:00:00Z',timing_status:'Xin muộn'}]});
      }return response({requests:[own,{request_id:'OTHER',canEdit:false,canManage:false}]});
    };
    await w.loadLeaveRequests();
    w.openLeaveDetail('OTHER');
    assert.equal(w.document.getElementById('leaveHistoryButton').hidden,true);
    await w.loadLeaveHistory('OTHER');
    assert.equal(histories,0);
    w.openLeaveDetail('OWN');
    await w.loadLeaveHistory('OWN');
    const text=w.document.getElementById('leaveHistoryBody').textContent;
    assert.match(text,/Xin muộn/);
    assert.match(text,/04\/10\/2026/);
    assert.match(text,/06\/10\/2026 01:30/);
  }finally{d.window.close();
  }});
test('manager schedules fetch and save nullable hours for selected employee date',async()=>{const d=page();
  const w=d.window;
  try{let save;
    w.fetch=async(url,o)=>{if(url==='/api/hr/employees')return response({employees:[{rowIndex:42,hoTen:'Nhân sự',boPhan:'Kho',coSo:'Hà Nội'}]});
      if(o?.method==='PUT'){save={url,body:JSON.parse(o.body)};
        return response({schedule:{version:2}});
      }return response({schedule:{morningStart:'08:00',afternoonStart:null,version:1}});
    };
    await w.openLeaveSchedule();
    w.document.getElementById('lsEmployee').value='42';
    w.document.getElementById('lsDate').value='2026-10-06';
    await w.loadLeaveSchedule();
    assert.equal(w.document.getElementById('lsMorning').value,'08:00');
    assert.equal(w.document.getElementById('lsAfternoon').value,'');
    await w.saveLeaveSchedule(event);
    assert.equal(save.url,'/api/hr/leave-work-schedules/42');
    assert.deepEqual(save.body,{date:'2026-10-06',morningStart:'08:00',afternoonStart:null});
  }finally{d.window.close();
  }});
test('manual absence uses linked employee ID and actual deadline without requiring schedule read permission',async()=>{const d=page(['hr.leave.absence.manage','hr.employees']);
  const w=d.window;
  try{let sent;
    w.fetch=async(url,o)=>{if(url==='/api/hr/employees')return response({employees:[{rowIndex:42,hoTen:'Nhân sự',boPhan:'Kho'}]});
      if(o?.method==='POST'){sent=JSON.parse(o.body);
        return response({error:'Chưa có lịch'},false,422);
      }return response({requests:[]});
    };
    await w.openManualAbsence();
    w.document.getElementById('maEmployee').value='42';
    for(const [id,v]of Object.entries({maStartDate:'2026-10-06',maEndDate:'2026-10-06',maStartSession:'Sáng',maEndSession:'Chiều',maLyDo:'Không báo'}))w.document.getElementById(id).value=v;
    await w.updateManualAbsencePreview();
    assert.match(w.document.getElementById('manualAbsenceDeadline').textContent,/04\/10\/2026/);
    await w.handleManualAbsenceSubmit(event);
    assert.equal(sent.hr_employee_id,42);
    assert.equal(w.document.getElementById('maLyDo').value,'Không báo');
    assert.equal(w.document.getElementById('manualAbsenceModal').hidden,false);
  }finally{d.window.close();
  }});

test('schedule save waits for loaded selection, failed load cannot clear persisted hours, reopening resets identity', async () => {
  const dom = page();
  const w = dom.window;
  try {
    const pending = [];
    const writes = [];
    w.fetch = async (url, options) => {
      if (url === '/api/hr/employees') return response({ employees: [{ id: 42, hoTen: 'A' }] });
      if (options?.method === 'PUT') { writes.push(JSON.parse(options.body));
        return response({ schedule: { version: 2 } });
      }
      return new Promise(resolve => pending.push(resolve));
    };
    await w.openLeaveSchedule();
    w.document.getElementById('lsEmployee').value = '42';
    w.document.getElementById('lsDate').value = '2026-10-06';
    const load = w.loadLeaveSchedule();
    assert.equal(w.document.getElementById('lsSave').disabled, true);
    await w.saveLeaveSchedule(event);
    assert.equal(writes.length, 0);
    pending[0](response({ error: 'Không có quyền' }, false, 403));
    await load;
    await w.saveLeaveSchedule(event);
    assert.equal(writes.length, 0);
    const retry = w.loadLeaveSchedule();
    pending[1](response({ schedule: { morningStart: '08:00', afternoonStart: '13:00', version: 1 } }));
    await retry;
    w.document.getElementById('lsMorning').value = '';
    w.document.getElementById('lsAfternoon').value = '';
    await w.saveLeaveSchedule(event);
    assert.deepEqual(writes, [{ date: '2026-10-06', morningStart: null, afternoonStart: null }]);
    await w.openLeaveSchedule();
    assert.equal(w.document.getElementById('lsEmployee').value, '');
    assert.equal(w.document.getElementById('lsDate').value, '');
    assert.equal(w.document.getElementById('lsSave').disabled, true);
  } finally { dom.window.close();
  }
});

test('leave boundary sorting is based on UTC calendar order without invented start hours', () => {
  const dom = page();
  try {
    assert.equal(dom.window.leaveBoundaryToTimestamp('Sáng 06/10/2026'), Date.UTC(2026, 9, 6));
    assert.equal(dom.window.leaveBoundaryToTimestamp('Chiều 06/10/2026'), Date.UTC(2026, 9, 6) + 1);
  } finally { dom.window.close();
  }
});

test('large continuous leave range keeps a bounded session UI and submits the full calendar; editing keeps stored subset', async () => {
  const dom = page(['hr.leave.submit']); const w = dom.window;
  try {
    const sent = [];
    const row = { request_id: 'LONG', canEdit: true, decision_version: 1, ly_do: 'Cũ', leave_sessions: [
      { date: '2026-01-01', session: 'Sáng' }, { date: '2030-12-31', session: 'Chiều' }
    ] };
    w.fetch = async (url, options) => {
      if (url.includes('/context')) return response({ eligible: true, profile: { hoTen: 'A' } });
      if (url.includes('/preview')) return response(preview);
      if (options?.method === 'POST') { sent.push(JSON.parse(options.body)); return response({ request: {} }); }
      return response({ requests: [row] });
    };
    await w.openSelfLeave(); dates(w, '2026-01-01', '2030-12-31');
    await w.updateSelfLeavePreview();
    assert.equal(w.document.querySelectorAll('#selfLeaveSessions input').length, 0);
    assert.match(w.document.getElementById('selfLeaveSessions').textContent, /toàn bộ|liên tục/i);
    await w.handleSelfLeaveSubmit(event);
    assert.equal(Object.hasOwn(sent[0], 'leave_sessions'), false);
    assert.equal(sent[0].end_date, '2030-12-31');
    await w.loadLeaveRequests(); await w.openSelfLeaveEdit('LONG');
    await w.handleSelfLeaveSubmit(event);
    assert.deepEqual(sent[1].leave_sessions, row.leave_sessions);
  } finally { dom.window.close(); }
});
